# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-loki
  description: Grafana Loki is a set of resources that can be combined into a fully featured logging stack
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
